

CREATE USER "Awards_Dev_User"  WITH
  PASSWORD 'Awards_Dev_User'
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  REPLICATION
  CONNECTION LIMIT -1
  VALID UNTIL '2035-12-29 23:10:38+02'
