--Access on the database for AwardsDbUser

GRANT TEMPORARY, CONNECT ON DATABASE "Awards_Dev" TO PUBLIC;

GRANT ALL ON DATABASE "Awards_Dev" TO "AwardsDbUser";

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO "AwardsDbUser";

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO postgres;